### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by BhawaniGarg** [ilomon10/twite#1]
Is this unfinished project?

**Comment by ilomon10** [comment]
This app need Twitter API key [`api/tweet/[id].js:L36`](https://github.com/ilomon10/twite/blob/main/pages/api/tweet/%5Bid%5D.js#L36)

You need to set your environment variable with [Twitter API](https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api) key.

```.env
# .env.local
TWITTER_ACCESS_TOKEN = CHANGE_THIS_WITH_TWITTER_API_KEY
```

And start your app `npm start` or `npm run dev`.

Please check this [preview site](https://twite.vercel.app) to see if its working with your tweet type.
