### ISSUE TITLE
Url Bug

### ISSUE THREAD

**Issue by BhawaniGarg** [ilomon10/twite#2]
Hi just got a bug in the codes. It doesnt show urls.
Original tweet: https://twitter.com/iAmBhawaniGarg/status/1505774634440204288

Photo generated from twite: https://i.imgur.com/BzgvkZb.png

You can see it has removed the URL from the original tweet.

**Comment by BhawaniGarg** [comment]
Update in this status i have entered 2 urls: https://twitter.com/iAmBhawaniGarg/status/1505779486306213888
But twite showing the first one only.

**Comment by ilomon10** [comment]
Fix df3f9f7628d79b0b866472d79b61184a4e37cb40
