### ISSUE TITLE
Extra Space

### ISSUE THREAD

**Issue by BhawaniGarg** [ilomon10/twite#4]
The generated images have some extra space between lines.. 
How it should look:
11111111111111111
22222222222222222

But how it look like:
11111111111111111

22222222222222222

**Comment by BhawaniGarg** [comment]
Screenshot: https://i.imgur.com/rMhnisd.png

**Comment by ilomon10** [comment]
Can you attach the specification of your environment?
For Example,

Platform: `Desktop`
Browser: `Google Chrome`
Browser Version: `99.0.4844.82 (Official build) (64-bit)`

**Comment by BhawaniGarg** [comment]
This error was with one single tweet only.
So closing it.
